### ISSUE TITLE
Can this package tackle with an image attach in content 

### ISSUE THREAD

**Issue by fpGHwd** [redguardtoo/org2nikola#11]
I found corresponding image in output/images is not correct in my website.

Website image is broken:
![image](https://user-images.githubusercontent.com/11605000/93018605-8088b880-f603-11ea-946f-2317308d07bb.png)

Part of content in nikola/posts/.wp file：
![image](https://user-images.githubusercontent.com/11605000/93018526-ecb6ec80-f602-11ea-9ea7-cdbb215589dc.png)

Fortunately the picture is in directory nikola/output/images/ , so only thing I need is chaning url of image in published files. Manually change url is not a convenient anyway.
![image](https://user-images.githubusercontent.com/11605000/93018769-c2fec500-f604-11ea-946c-76bb8ee595b1.png)

What can I do to get correct image url when I want to output contents with image to github.io and display picture properly? Are there some hooks?

Thank you for any advice...

**Comment by fpGHwd** [comment]
I think maybe it's the nikola build's responsibility to change the url.

**Comment by redguardtoo** [comment]
Check the latest code, I added `org2nikola-process-output-html-function`. You can customize html output.

Please note how the html is rendered is decided by export functions of `org-mode`.

**Comment by fpGHwd** [comment]
Thanks, I'll try it now

**Comment by fpGHwd** [comment]
It works, thank you very much!
