### ISSUE TITLE
Set tags

### ISSUE THREAD

**Issue by drym3r** [redguardtoo/org2nikola#8]
It would be awesome if it could be set something like #+Tags: emacs to the org node and be added to the post meta file.

**Comment by redguardtoo** [comment]
sure. That's doable, but org-mode already support tags by `M-x org-ctrl-c-ctrl-c`? why you want to add tags to `#+Tags:` property?

**Comment by drym3r** [comment]
Well, I don't mind the method, I only would like the feature to use nikola tags.

**Comment by redguardtoo** [comment]
got, press `C-c C-c` or `M-x org-ctrl-c-ctrl-c`, input tags separated by ":", for example,  `:en:ispell:aspell:spell:check:emacs:hunspell:`, that's all you need to do.

**Comment by drym3r** [comment]
Wow, thank you very much. I recommend you to add it on the readme, it's not there.
